### ISSUE TITLE
silex/emacs:25 and silex/emacs:25.3 are different images

### ISSUE THREAD

**Issue by Silex** [Silex/docker-emacs#14]
```
silex/emacs                     25                  6a84337fb723        15 hours ago        997MB
silex/emacs                     25.3                6327e8b8c02f        15 hours ago        997MB
```

I think what happens is that because we use the build cache, once the images are different they will always remain different. If you look at https://travis-ci.org/Silex/docker-emacs/jobs/344693765 it looks like this is what happens as each tags get pulled and used as cache.

@gonewest818: what do you reckon the right fix would be? Right now I'm thinking of:

- Use a convention, like "always use the first tag as the build cache".
- Add some other var in the matrix, like MAIN_TAG

I'm in favor of the first one as it's simpler for now, I'll commit this and we can refactor later.

**Comment by Silex** [comment]
Ok my fix works as expected.

**Comment by gonewest818** [comment]
It might be best to have a way to ask for “—no-cache” builds of everything as a feature in functions.sh. 

In this particular case though, I noticed in the slim work that it’s not really necessary to iterate the builds like “for tag in $DOCKER_TAGS; do docker build ...” because they’re all building the same $GIT_BRANCH. So I’m changing that loop by building each GIT_BRANCH once, and then looping over the tags. That should prevent these from getting out of sync further.
