### ISSUE TITLE
Make is not available in some images

### ISSUE THREAD

**Issue by DamienCassou** [Silex/docker-emacs#26]
Strangely enough, it seems that images don't have `make` available (even though it is used to build emacs):

- Always fails with Emacs 26: https://gitlab.petton.fr/mpdel/libmpdel/-/jobs/2157
- Always fails with Emacs 25.3: https://gitlab.petton.fr/mpdel/libmpdel/-/jobs/2158

**Comment by Silex** [comment]
Thank you for the report.

Well that is expected, only the `-dev` images contains the dev tools now.

With the recent changes probably that some old images where intermixed with the new ones, hence your intermittent failures. This should be consistent now.

**Comment by Silex** [comment]
@DamienCassou: btw, do you have an interest for `24.2` and `24.1` images?

**Comment by DamienCassou** [comment]
On April 4, 2018 8:36:56 PM GMT+02:00, Philippe Vaucher <notifications@github.com> wrote:
>Well that is expected, only the `-dev` images contains the dev tools
>now.

Make is used to build emacs and I don't see any instruction removing it. Can you please explain?
-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by DamienCassou** [comment]
On April 4, 2018 8:41:50 PM GMT+02:00, Philippe Vaucher <notifications@github.com> wrote:
>@DamienCassou: btw, do you have an interest for `24.2` and `24.1`
>images?

Not really

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by Silex** [comment]
> Make is used to build emacs and I don't see any instruction removing it. Can you please explain?

I'm not sure what the real question is so I'll just give you detailed informations:

- The main images (~450MB) only contain the runtime dependencies for Emacs to run.
- The `-dev` variants (~1200MB) contain additional developer tools such as [Cask](https://cask.readthedocs.io), [git](https://git-scm.com) or [Python](https://www.python.org),
  and the Emacs source is available at `/opt/emacs` if you need to build Emacs differently.

This is the `25.3` Dockerfile: https://github.com/Silex/docker-emacs/blob/master/25.3/xenial/Dockerfile

As you see, `25.3` only contains the emacs binaries because of the multi-stage build. That a bit the equivalent of `apt-get install emacs`.

Do you think `make` should be available in all images? Is there a problem using the `-dev` image?

**Comment by DamienCassou** [comment]
Philippe Vaucher <notifications@github.com> writes:
> [...]
> As you see, `25.3` only contains the emacs binaries because of the
> multi-stage build. That a bit the equivalent of `apt-get install
> emacs`.


I understand how things work now. Thank you!


> Do you think `make` should be available in all images? Is there a problem using the `-dev` version?


I will use the dev-version if Cask don't get in my way. Thanks.

You can close the issue now.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by Silex** [comment]
Alright, reopen if needed.

**Comment by Silex** [comment]
@DamienCassou: just curious, is gitlab free? I seem to remember it has its own docker registry, which could simplify my workflow for caching the intermediate layers to solve issues I have with the refactoring. The website is rather confusing about how it compares to travis-ci.

**Comment by jgkamat** [comment]
I think with the free plan, you get `2,000` pipeline minutes per month: https://about.gitlab.com/2017/04/11/introducing-subscriptions-on-gitlab-dot-com/. 

I've used it for a couple of my projects, and it's a lot better than other free services (travis,circle), but worse than jenkins in my opinion.

Edit: The limit may be higher (or removed) for public projects, docs for these things are really annoyingly hard to find.

**Comment by Silex** [comment]
@jgkamat: thanks for the input! So... `2000 / 31 = 64.5161290323` that makes about 1 hour a day, which should be enough for the daily build.

I'll check and probably switch to it if it's better than travis.

**Comment by DamienCassou** [comment]
Philippe Vaucher <notifications@github.com> writes:
> @DamienCassou: just curious, is gitlab free?

Gitlab CE is a free open-source software you can install anywhere you
like (some of my projects are at https://gitlab.petton.fr/).

Gitlab EE is a software based on Gitlab CE with additional features but
is closed source and not free.

gitlab.com is an instance of Gitlab EE that anyone can use for no cost
but with some restrictions.

> I seem to remember it has its own docker registry

There is a docker registry for each project. My experiment to do
something similar than this project is hosted at:

https://gitlab.com/DamienCassou/emacs-ci-docker

The corresponding docker registry is at

https://gitlab.com/DamienCassou/emacs-ci-docker/container_registry

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by Silex** [comment]
@DamienCassou: right, I found your project after my comment, the private registry looks neat!

Thank you for the info, I might consider gitlab-ce at work for continuous integration.

@jgkamat: if I may, where does Jenkish shine compared to gitlab-ce? My guess is that Jenkins is more flexible because it can also run VMs etc.

**Comment by jgkamat** [comment]
Yup, I really like jenkins mostly because it's a lot more flexible. It has a really great plugin interface, which allows it to do pretty much anything you want (as there's a plugin for almost all triggers and actions you can think of). For example [here's an android emulator for jenkins](https://plugins.jenkins.io/android-emulator), which would be hard to emulate on the other standard systems. Another one is this [flakey test handler](https://wiki.jenkins.io/display/JENKINS/Flaky+Test+Handler+Plugin) which automatically figures out if a test is flakey (no more guessing if you broke a test or if it's just flaky).

I also liked the UI for configuring it quite a bit, I found it a lot more intuitive than the commercial options.

The downside (of course) is that you have to self-host it, and that's probably not worth it unless you're a very large project that has to have the best CI.

**Comment by Silex** [comment]
@jgkamat: we used to have jenkins at work before, but then someone broke it and we moved to a new architecture and everyone was swamped and it never came back. I'm pushing to bring back some form of CI, so the more info I have the better.

Thank you very much for your insights! :+1:
