### ISSUE TITLE
emacs-24.1 and emacs-24.2

### ISSUE THREAD

**Issue by phillord** [Silex/docker-emacs#37]
I would like to add images for Emacs-24.1 and emacs-24.2. As I know you are aware, this currently runs into the problem that was reported here:

https://stackoverflow.com/questions/37544423/how-to-build-emacs-from-source-in-docker-hub-gap-between-bss-and-heap

You own solution works quite well and allows building of this image. However, I don't understand enough of the issue to know whether if this were published to docker hub if would still work (i.e. is it only during dumping). Are you interested in the PR?

On a different topic, just discovered this project -- many thanks, keeping Emacs-24 building on my development machines has got more and more difficult over time.

**Comment by Silex** [comment]
Hello! Yeah this https://github.com/moby/moby/issues/22801 is also worth reading if you are interested in this issue. All the emacs images currently suffer from this, but there is hope for the future `26.3` to be finally free of this problem (see the pdumper threads on emacs-devel).

Building `24.1` or `24.2` and then pushing to the registry would work. It's just when building the image that `/proc/sys/kernel/randomize_va_space` needs to be disabled, and it happens that it is on travis so I'm able to build the images (of course if you try to `dump-emacs` while using emacs it will not work, but almost nobody does that, and you can apply the same trick to get around this).

We *could* build 24.1 & 24.2 but there was not enough interest (see #26) for such "old" images, and 24.3 is enough for most people's tests.

My rule of thumb is something like "for old major versions, keep the latest version only". Theorically that means I'd drop `25.1` and `25.2`... oh well, let's vote!

@DamienCassou, @gonewest818, @jgkamat, @phillord:

* Should we add `24.1` and `24.2`?
* If no, should we drop `25.1` and `25.2`?

Thanks :+1:

**Comment by DamienCassou** [comment]
I have no opinion on whether to keep old images or not. What is your use-case @phillord for old images?

**Comment by phillord** [comment]
I am using the old images to test my own package assess which currently supports all of the Emacs-24 series (in so far as I am able to test them). As my OS gets more recent, it gets harder to build 24, requiring patching.

I am happy to accept that with Emacs-24.3 available, I can probably claim to support all of Emacs-24 (the significant changes between 24.3 and 24.4 means I cannot give this statement with just 24.5).

I plan to drop Emacs-24 when Emacs-27 is released, but would like to maintain this till then. I think "support all of the last major version" is reasonable. I realise that just before a major release that means support very old versions.

@silex pdumper is actually on master so should come out on Emacs-27. My guess would be that because of its arrival, we will get an Emacs-27 branch fairly soon. 

I guess the point is that I am not using docker-emacs only in batch, for running ert. I realise that this may well not be your intended use case, but it is kind of handy for this.

**Comment by Silex** [comment]
Wait I messed up. For a while I thought `24.3` was the latest in the `24` series, but there's `24.4` and `24.5`. So the ones left out are `24.2`, `24.1`, `23.3`, `23.2`, etc. If I recall correctly building `< 23.4` is a PITA.

You raise an important point tho, instead of focusing on the numbers we can focus on the important changes. You say that between `24.3` and `24.4` there was a lot of changes to it makes sense to have these versions available.

So, what other version which is not the latest of a major version makes sense?

**Comment by phillord** [comment]
Well, you have 23.4. So this is 7 years old and it's good to have in a "I can run Emacs that old" kind of way, but probably not much more. 24.4 bought in the new advice system -- so assess loses functionality in 24.3 and earlier. Of course, there may be other changes that affect other packages. Now 23.4 and 24.1 came out in the same year, so perhaps is also only good in a "I can run Emacs that old" way, although 23.4 was really just an emergency bug fix for 23.3. Most of the code is a year and bit older than 24.1.

For me, 24.1 and 24.2 are only for completeness sake, but having them for the next year or so (at a guess) till 27 comes out would be nice, but I'd fully understand if you didn't want them. 

What would be really nice would be Emacs-17, cause that's the first one I ever used. Not holding out any hope here....

**Comment by jgkamat** [comment]
>* Should we add `24.1` and `24.2`?
>* If no, should we drop `25.1` and `25.2`?


Is there any advantage to dropping them (eg: making this an automated build?).

I do like having older versions around so I can run my tests against old Emacs versions, but at some point people do have to upgrade. Right now my packages support a min version of 25 though, so it would be nice to at least keep that around.

If its trouble to maintain, we might consider a seperate archive hub repo and use that for very old releases instead?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Silex** [comment]
> For me, 24.1 and 24.2 are only for completeness sake, but having them for the next year or so (at a guess) till 27 comes out would be nice, but I'd fully understand if you didn't want them.
> What would be really nice would be Emacs-17, cause that's the first one I ever used. Not holding out any hope here....

I see. I'll check how easy it is to compile older version than `23.4` to see what is feasible or not before deciding of a policy, like "all emacs version above X".

**Comment by Silex** [comment]
> Is there any advantage to dropping them (eg: making this an automated build?). 

Cleaner https://hub.docker.com/r/silex/emacs page. I'm not a fan of having a huge wall of tags, at the same time I just realised I could format it like:

* 26.2 (dev, alpine, alpine-dev)

instead of:

* 26.2 (26.2/ubuntu/18.04/Dockerfile)
* 26.2-dev (26.2/ubuntu/18.04/Dockerfile)
* 26.2-alpine (26.2/alpine/3.7/Dockerfile)
* 26.2-alpine-dev (26.2/alpine/3.7/Dockerfile)

> I do like having older versions around so I can run my tests against old Emacs versions, but at some point people do have to upgrade. Right now my packages support a min version of 25 though, so it would be nice to at least keep that around.

I hear you.

> If its trouble to maintain, we might consider a seperate archive hub repo and use that for very old releases instead?

Yeah the limit we will probably hit soonish is travis-ci's cache. Right now we use around 1.2 GB for it but I know that in previous tests it stopped working when we were around 2 GB. I couldn't find the exact limit or if it was simply a "timeout" limit, e.g caches that are too big takes too long to restore and the job times out.

@DamienCassou: do you happen to know what the cache limit in gitlab is? Can't find it either.

We need the cache to benefit from "docker build" cache mechanism, otherwise new images are built all the time even if nothing changed in the image. I guess I could work around this by caching the medatas (file timestamps) instead of caching the files, which would results in a very low size cache. That'd also probably speed up the builds quite a lot! Maybe I can even ask git to set the right timestampts for me. I'll do some checks :heart_eyes:

**Comment by phillord** [comment]
@silex Am really joking about versions older than 23.4....

**Comment by Silex** [comment]
> @Silex Am really joking about versions older than 23.4....

I was considering going `22+` for fun's sake, but maybe only build latest for 22-23. I guess it won't build anyway, will keep you posted.

**Comment by DamienCassou** [comment]
Philippe Vaucher <notifications@github.com> writes:
> @DamienCassou: do you happen to know what the cache limit in gitlab
> is? Can't find it either.


I guess that on a self-hosted gitlab or gitlab's runner, you define your
own limits. I don't know about gitlab.com's shared runners.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by Silex** [comment]
Alright, interesting findings:

* Emacs 24.2 and 24.1 only build with "make" (and not "make -j 8")
* Emacs 23.2 and downward do not build because of https://debbugs.gnu.org/cgi/bugreport.cgi?bug=5857

This means 24.2 and 24.1 could easily be built but anything 23.4 kinda is a PITA. So I guess the rule will be "all version over 23.4".

**Comment by phillord** [comment]
Not surprised about `-j 8`. Supporting a parallel build didn't used to be a thing; now I think everyone builds this way.

**Comment by Silex** [comment]
Alright, added 24.2 and 24.1. Had originally refactored for build arguments in order to pass `$(nproc)` or `1` but some issues appeared so I simply removed `-j 8` for old images. 

Thanks everyone :+1:

**Comment by phillord** [comment]
Thank you! Images used and tested. And my code is working also which makes me happy.
