### ISSUE TITLE
`(void-function image-transforms-p)` in emacs 28.2 CI / cask tests

### ISSUE THREAD

**Issue by mooseyboots** [Silex/docker-emacs#92]
hi, and first off thanks for your builds.

i use them for https://codeberg.org/martianh/mastodon.el/, and CI tests with codeberg's woodpecker. a while back my tests started breaking with `(void-function image-transforms-p)`, when building your `silex/emacs:cask`, which is currently 28.2. as far as i understand that function isn't in a library that needs loading separately, and it worked in the tests for a long time prior.

has anything changed with the builds that could trigger such an error? otherwise i'm a bit flummoxed as to how my code/tests could suddenly cause such a failure.

**Comment by Silex** [comment]
Ah, yes I think it's because the images are not build with GUI support anymore (and thus images support), I had too many issues (see #62).

Basically I had my own fork of nix-emacs-ci that added GUI support and it kept breaking and I don't have time to fight with emacs building anymore. If you want to push for GUI support please check https://github.com/purcell/nix-emacs-ci/pull/49, or maybe you can create an issue to ask for just ImageMagick support so images support should work.

I also plan on removing the dev images they are useless :disappointed: 

I'll update the README to remove the GUI part
